// <auto-generated />
using DnDApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace DndApi.Migrations
{
    [DbContext(typeof(MonsterContext))]
    [Migration("20171113080752_AddMonsters")]
    partial class AddMonsters
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("DnDApi.Models.Monster", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("actions");

                    b.Property<string>("alignment");

                    b.Property<int>("armor_class");

                    b.Property<int>("challenge_rating");

                    b.Property<int>("charisma");

                    b.Property<int>("charisma_save");

                    b.Property<string>("condition_immu");

                    b.Property<int>("constitution");

                    b.Property<string>("damage_immu");

                    b.Property<string>("damage_res");

                    b.Property<string>("damage_vuln");

                    b.Property<int>("dexterity");

                    b.Property<int>("dexterity_save");

                    b.Property<string>("hit_dice");

                    b.Property<int>("hit_points");

                    b.Property<int>("intelligence");

                    b.Property<string>("languages");

                    b.Property<string>("name");

                    b.Property<int>("perception");

                    b.Property<string>("senses");

                    b.Property<string>("size");

                    b.Property<string>("special_abilities");

                    b.Property<string>("speed");

                    b.Property<int>("stealth");

                    b.Property<int>("strength");

                    b.Property<string>("subtype");

                    b.Property<string>("type");

                    b.Property<int>("wisdom");

                    b.Property<int>("wisdom_save");

                    b.HasKey("id");

                    b.ToTable("Monsters");
                });
#pragma warning restore 612, 618
        }
    }
}
